[package]
name = "rinha_parser"
version = "0.1.0"
authors = []
edition = "2021"

[lib]
name = "rinha_parser"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
rustler = "0.29.1"
rinha = "0.0.5"
serde = { version = "1.0.188", features = ["derive"] }
serde_json = "1.0.105"
